### ISSUE TITLE
Prepare and Release Migaloo-frontend to public (open-source)

### ISSUE THREAD

**Issue by 0xFable** [White-Whale-Defi-Platform/white-whale-frontend#104]
Related PR #95 

We need: 
- [X] Contributing, Code of conduct, security docs #95  
- [X] Pull request and issue templates #95  
- [X] Precommit hook scripts or integration with husky #95  
- [X] Improved readme linking to all the above as well as docs #95  
- [X] Add tests husky hook such that tests are run before push #95 
- [X] Add basic CI setup #110 
- [ ] Open Source the frontend 🥂 -- Today :D
